import colors from "./colors";

export default {
  light: {
    background: colors.white,
    onBackground: colors.white,
    border: colors.grey2,
    typography: {
      color: colors.black,
      heading: colors.black,
      body: colors.black,
      inverted: colors.white,
      disabled: colors.grey4,
      placeholder: colors.grey4,
    },
    cta: {
      primary: "#F7933B",
      dark: "#984A04",
      midDark: "#D46706",
      midLight: "#FAAB65",
      light: "#FFEEDE",
    },
    success: {
      primary: "#86C840",
      dark: "#216F0E",
      midDark: "#61A52D",
      midLight: "#C4E4A1",
      light: "#F1F9E8",
    },
    error: {
      primary: "#F24851",
      dark: "#BA071F",
      midDark: "#E82637",
      midLight: "#F09T9A",
      light: "#FFEAEE",
    },
    info: {
      primary: "#2BB9F5",
      dark: "#0B5C99",
      midDark: "#1AA0E2",
      midLight: "#B5E6FA",
      light: "#E2F5FE",
    },
    warning: {
      primary: "#FEDC56",
      dark: "#B18E00",
      midDark: "#EDBE04",
      midLight: "#FEF4AB",
      light: "#FFFDEB",
    },
  },
  dark: {
    background: colors.black,
    onBackground: colors.grey8,
    border: colors.grey6,
    typography: {
      color: colors.grey1,
      heading: colors.grey1,
      body: colors.grey2,
      inverted: colors.grey8,
      disabled: colors.grey4,
      placeholder: colors.grey4,
    },

    cta: {
      primary: "#F7933B",
      dark: "#311D0C",
      midDark: "#984A04",
      midLight: "#FAAb65",
      light: "#FFEEDE",
    },
    success: {
      primary: "#86C840",
      dark: "#1B280D",
      midDark: "#216F0E",
      midLight: "#C4E4A1",
      light: "#F1F9E8",
    },
    error: {
      primary: "#F24851",
      dark: "#300E10",
      midDark: "#BA071F",
      midLight: "#F09T9A",
      light: "#FFEAEE",
    },
    info: {
      primary: "#2BB9F5",
      dark: "#092531",
      midDark: "#0B5C99",
      midLight: "#B5E6FA",
      light: "#E2F5FE",
    },
    warning: {
      primary: "#FEDC56",
      dark: "#332C11",
      midDark: "#B18E00",
      midLight: "#FEF4AB",
      light: "#FFFDEB",
    },
  },
};
