name: Release & Deploy storybook

on:
  push:
    branches: [master]
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2.1.2
      - name: Install
        run: |
          cd example
          yarn
          cd ..
          yarn
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Build storybook
        run: | 
          cd example 
          yarn build-storybook -o public
        env: 
          INPUT_TOKEN: ''
      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_pages
          folder: example/public
