name: Release & Deploy storybook

on:
  push:
    branches: [master]
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - name: Install
        run: |
          cd example
          yarn
          cd ..
          yarn
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Deploy storybook
        run: |
          cd example 
          npm run deploy-storybook -- --ci -t=${{ secrets.GITHUB_TOKEN }}
